export const RMU = {};

// http://www.zorro.20m.com/rolemaster/sw_races_languages_conversion.htm
RMU.languageslist = {
	"erlin": "Erlin",
	"iylar": "Iylar",
	"rhaya": "Rhaya",
	"miir": "Miir",
	"shay": "Shay",
	"taal": "Taal",
	"enris": "Enris",
	"aludos": "Aludos",
	"enruth": "Enruth",
	"kronyt": "Kronyt",
	"logos": "Logos",
	"uscurac": "Uscurac",
	"xytos": "Xytos"
}

RMU.statslist = {
	"none":	"",
	"ag": 	"RMU.stats.ag",
	"co": 	"RMU.stats.co",
	"em": 	"RMU.stats.em",
	"in": 	"RMU.stats.in",
	"me": 	"RMU.stats.me",
	"pr": 	"RMU.stats.pr",
	"qu": 	"RMU.stats.qu",
	"re": 	"RMU.stats.re",
	"sd": 	"RMU.stats.sd",
	"st": 	"RMU.stats.st"
}

RMU.skillcategorieslist = {
	"none":							"",
	"animal": 					"RMU.skillcategories.animal",
	"awareness": 				"RMU.skillcategories.awareness",
	"battleExpertise": 	"RMU.skillcategories.battleExpertise",
	"bodyDiscipline": 	"RMU.skillcategories.bodyDiscipline",
	"brawn": 						"RMU.skillcategories.brawn",
	"combatExpertise": 	"RMU.skillcategories.combatExpertise",
	"combatTraining": 	"RMU.skillcategories.combatTraining",
	"composition": 			"RMU.skillcategories.composition",
	"crafting": 				"RMU.skillcategories.crafting",
	"delving": 					"RMU.skillcategories.delving",
	"environmental": 		"RMU.skillcategories.environmental",
	"gymnastic": 				"RMU.skillcategories.gymnastic",
	"lore": 						"RMU.skillcategories.lore",
	"languages": 				"RMU.skillcategories.languages",
	"magicalExpertise": "RMU.skillcategories.magicalExpertise",
	"medical": 					"RMU.skillcategories.medical",
	"mentalDiscipline": "RMU.skillcategories.mentalDiscipline",
	"movement": 				"RMU.skillcategories.movement",
	"performanceArt": 	"RMU.skillcategories.performanceArt",
	"science": 					"RMU.skillcategories.science",
	"social": 					"RMU.skillcategories.social",
	"subterfuge": 			"RMU.skillcategories.subterfuge",
	"technical": 				"RMU.skillcategories.technical",
	"vocation": 				"RMU.skillcategories.vocation"
}

RMU.attacktableslist = {
	"none":						"",
	"armingSword": 		"RMU.attacktables.armingSword",
	"coldBall": 			"RMU.attacktables.coldBall",
	"fireBall": 			"RMU.attacktables.fireBall",
	"lightningBall": 	"RMU.attacktables.lightningBall",
	"battleAxe": 			"RMU.attacktables.battleAxe",
	"beak": 					"RMU.attacktables.beak",
	"bite": 					"RMU.attacktables.bite",
	"bola": 					"RMU.attacktables.bola",
	"fireBolt": 			"RMU.attacktables.fireBolt",
	"iceBolt":				"RMU.attacktables.iceBolt",
	"lightningBolt": 	"RMU.attacktables.lightningBolt",
	"waterBolt": 			"RMU.attacktables.waterBolt",
	"longBow": 				"RMU.attacktables.longBow",
	"shortBown": 			"RMU.attacktables.shortBown",
	"broadsword": 		"RMU.attacktables.broadsword",
	"claw": 					"RMU.attacktables.claw",
	"club": 					"RMU.attacktables.club",
	"crossbow": 			"RMU.attacktables.crossbow",
	"crush": 					"RMU.attacktables.crush",
	"dagger": 				"RMU.attacktables.dagger",
	"falchion": 			"RMU.attacktables.falchion",
	"fightingStick": 	"RMU.attacktables.fightingStick",
	"flail": 					"RMU.attacktables.flail",
	"grapple": 				"RMU.attacktables.grapple",
	"horn": 					"RMU.attacktables.horn",
	"mace": 					"RMU.attacktables.mace",
	"ram": 						"RMU.attacktables.ram",
	"rapier": 				"RMU.attacktables.rapier",
	"rock": 					"RMU.attacktables.rock",
	"scimitar": 			"RMU.attacktables.scimitar",
	"shield": 				"RMU.attacktables.shield",
	"sling": 					"RMU.attacktables.sling",
	"spear": 					"RMU.attacktables.spear",
	"stinger": 				"RMU.attacktables.stinger",
	"trample": 				"RMU.attacktables.trample",
	"unarmedStrikes": "RMU.attacktables.unarmedStrikes",
	"unarmedSweeps": 	"RMU.attacktables.unarmedSweeps",
	"warHammer": 			"RMU.attacktables.warHammer",
	"whip": 					"RMU.attacktables.whip"
}